# Generated by Django 3.1.1 on 2020-10-14 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addnews',
            name='image_url',
        ),
    ]
