# Generated by Django 3.1.1 on 2020-10-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_added',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='post_date',
            field=models.DateField(null=True),
        ),
    ]
